INSERT INTO tb_category(created_at, created_by, updated_at, updated_by, name) VALUES (NOW(),'icaro',null,null,'Eletrônicos');
INSERT INTO tb_category(created_at, created_by, updated_at, updated_by, name) VALUES (NOW(),'icaro',null,null,'Livros');
INSERT INTO tb_category(created_at, created_by, updated_at, updated_by, name) VALUES (NOW(),'icaro',null,null,'Esportes');
INSERT INTO tb_category(created_at, created_by, updated_at, updated_by, name) VALUES (NOW(),'icaro',null,null,'Eletrodomésticos');

INSERT INTO tb_product(created_at, created_by, updated_at, updated_by, name, description, price, quantity, image_url, slug, active) VALUES (NOW(),'icaro',null,null,'Notebook asus vivobook','É leve. É compacto. É o ASUS Vivobook Go 15. Projetado para torná-lo produtivo e mantê-lo entretido onde quer que você vá! Com processador AMD Ryzen 5 7520U de excelente desempenho, 16 GB de memória RAM LPDDR5 e até 512 GB de SSD , ele é perfeito para seu dia a dia.',2867.00, 50, 'img/notebook-asus-vivobook','notebook-asus-vivobook', 1);
INSERT INTO tb_product(created_at, created_by, updated_at, updated_by, name, description, price, quantity, image_url, slug, active) VALUES (NOW(),'icaro',null,null,'As Crônicas de Nárnia','As Crônicas de Nárnia – Coleção de Luxo: O Leão, a Feiticeira e o Guarda-Roupa", de C.S. Lewis, é a edição de luxo de um dos livros mais icônicos da literatura infantil. Esta obra é a primeira da famosa série As Crônicas de Nárnia, que transporta os leitores para um mundo mágico e cheio de aventuras.',41.76, 100, 'img/as-cronicas-de-narnia','as-cronicas-de-narnia', 1);
INSERT INTO tb_product(created_at, created_by, updated_at, updated_by, name, description, price, quantity, image_url, slug, active) VALUES (NOW(),'icaro',null,null,'Halter 4kg','O Halter Emborrachado Para Academia e Clínicas de Fisioterapia - Un - 4 Kg é a escolha ideal para quem busca qualidade e segurança em seus treinos. Com um design hexagonal, este halter proporciona uma melhor estabilidade durante os exercícios, evitando que role no chão. Fabricado em PVC e ferro, seu revestimento emborrachado garante uma aderência superior, permitindo que você mantenha o controle total durante suas atividades.',56.20, 200, 'img/halter-4kg','halter-4kg', 1);
INSERT INTO tb_product(created_at, created_by, updated_at, updated_by, name, description, price, quantity, image_url, slug, active) VALUES (NOW(),'icaro',null,null,'Samsung Galaxy A35','O Galaxy A35 256GB oferece uma experiência única de desempenho e conectividade. Com um processador Octa Core veloz e uma tela Super AMOLED de alta qualidade, você desfrutará de imagens nítidas e cores vibrantes em um display de 6.6 polegadas.',1495.12, 75, 'img/samsung-galaxy-a35','samsung-galaxy-a35', 1);
INSERT INTO tb_product(created_at, created_by, updated_at, updated_by, name, description, price, quantity, image_url, slug, active) VALUES (NOW(),'icaro',null,null,'Geladeira Philco','Desfrute da frescura de seus alimentos e armazene-os de maneira prática e confortável na sua geladeira Philco, a protagonista da sua cozinha.',5519.88, 30, 'img/geladeira-philco','geladeira-philco', 1);
INSERT INTO tb_product(created_at, created_by, updated_at, updated_by, name, description, price, quantity, image_url, slug, active) VALUES (NOW(),'icaro',null,null,'Torradeira Elétrica','Você lembra do aroma clássico das torradas frescas na casa da vovó? Que tal um grande café da manhã com manteiga e geleia? Com a torradeira Eletrolux Torradeira eletrica cabe pao frances electrolux 110v você garantirá um resultado uniforme e crocante.',181.00, 65, 'img/torradeira-eletrica','torradeira-eletrica', 1);
INSERT INTO tb_product(created_at, created_by, updated_at, updated_by, name, description, price, quantity, image_url, slug, active) VALUES (NOW(),'icaro',null,null,'Ducha Jet','Com mais de 50 anos de fabricação de chuveiros elétricos, a Lorenzetti é uma empresa líder no campo criando produtos de excelência. Desta forma, você poderá desfrutar de qualidade e design exclusivo em seu banheiro.',182.16, 120, 'img/ducha-jet','ducha-jet', 1);
INSERT INTO tb_product(created_at, created_by, updated_at, updated_by, name, description, price, quantity, image_url, slug, active) VALUES (NOW(),'icaro',null,null,'Livro Harry Potter e a Pedra Filosofal','A história, recheada de fantasmas, paredes que falam, caldeirões, sapos, unicórnios, dragões e gigantes, transcende um simples passatempo',41.56, 190, 'img/pedra-filosofal','pedra-filosofal', 0);

INSERT INTO tb_product_category(product_id,category_id) VALUES(1,1);
INSERT INTO tb_product_category(product_id,category_id) VALUES(2,2);
INSERT INTO tb_product_category(product_id,category_id) VALUES(3,3);
INSERT INTO tb_product_category(product_id,category_id) VALUES(4,1);
INSERT INTO tb_product_category(product_id,category_id) VALUES(5,4);
INSERT INTO tb_product_category(product_id,category_id) VALUES(6,4);
INSERT INTO tb_product_category(product_id,category_id) VALUES(7,4);
INSERT INTO tb_product_category(product_id,category_id) VALUES(8,2);